config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :welcome, only: [:index]
  resources :users, only: [:new, :show, :create]
  resources :messages, only: [:new, :show, :create, :update]
  resources :sessions, only: [:create, :new]

  get 'login' => 'sessions#new'
  get 'signup' => 'users#new'
  post 'logout' => 'sessions#destroy'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :password, on: :create

  has_many :sent_messages, foreign_key: 'sender_id'
  has_many :received_messages, foreign_key: 'receiver_id'

  def update_karma(message)
    receiver = User.find(message.receiver.id)
    karma = self.karma
    message.thumbs_up ? karma += 1 : karma -= 1
    self.update(karma: karma)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :html, :js

  def new
    @sender = current_user
    @message = Message.new
  end

  def show
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to user_path(current_user)
    else
      flash.now.alert = "Something went wrong. It's probably not your fault."
      render 'new'
    end
    @message.update(receiver_id: new_receiver.id)
  end

  def update
    @message = Message.find(params[:id])
    @sender = User.find(@message.sender_id)
    @message.update(thumbs_up: message_params[:thumbs_up])
    @sender.update_karma(@message)
    Message.destroy(@message.id)
    redirect_to user_path(current_user)
  end

  private
    def message_params
      params.require(:message).permit(:content, :sender_id, :thumbs_up)
    end

    def new_receiver
      num_users = User.all.length
      User.find(rand(num_users + 1))
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_handle(user_params[:handle])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), :notice => "Welcome, #{@user.handle}"
    else
      flash.now.alert = "Incorrect username or password."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

  private
    def user_params
      params.require(:user).permit(:handle, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Signed Up"
    else
      render 'new'
    end
  end

  def show
    @user = current_user
    @new_messages = Message.where(receiver_id: @user.id)
    @sent_messages = Message.where(sender_id: @user.id)
  end

  private
    def user_params
      params.require(:user).permit(:handle, :password, :karma)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageInABottle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%if @current_user %>
  <%= link_to "logout", {controller: "sessions", action: "destroy"}, method: :post%>
<%else%>
  <%= link_to "sign in", new_session_path %>
  <%= link_to "sign up", new_user_path %>
<%end%>

</body>
</html>

app/views/messages/_show.html.haml
="Karma: #{message.sender.karma}"
=message.content + message.id.to_s
=form_for :message, remote: true, url: {controller: 'messages', action: 'update'}, method: :put do |f|
  =f.radio_button(:thumbs_up, true)
  =label_tag(:thumbs_up_true, 'Thumbs Up')
  =f.radio_button(:thumbs_up, false)
  =label_tag(:thumbs_up_false, 'Thumbs Down')

  =f.submit :class => 'message_update'

app/views/messages/new.html.haml
=form_for :message, url: {action: 'create'} do |f|
  =f.text_field :content, placeholder: 'type your message here'
  =f.hidden_field :sender_id, value: @sender.id
  =f.submit

app/views/users/new.html.haml
%h1
  Sign Up

=form_for :user, url: {action: 'create'} do |f|
  =f.text_field       :handle, placeholder: 'username'
  =f.password_field   :password, placeholder: 'password'
  =f.hidden_field     :karma, value: 0
  =f.submit

app/views/users/show.html.haml
%h1
  ="Welcome, #{@user.handle}!"

%h3
  New Messages
%p
  -@new_messages.each do |m|
    %div.message_sender
      =link_to m.sender.handle, user_path(@user) if m.sender
      %div.message_content
        =render :partial => 'messages/show', locals: {message: m}
    %br
%h3
  Sent Messages
%p
  -@sent_messages.each do |m|
    =m.receiver.handle if m.receiver
    =m.content
    %br

app/views/welcome/index.haml
%h1
  Welcome to Message in a Bottle
%h3
  Not affiliated with Sting in any way shape or form.
%h5
  Fuck Sting.
%h6
  Although the Police had a few decent tunes.  I quite like Roxanne.

app/views/welcome/index.html.haml
%h1
  Welcome to Message in a Bottle
%h3
  Not affiliated with Sting in any way shape or form.
%h5
  Fuck Sting.
%h6
  Although the Police had a few decent tunes.  I quite like Roxanne.

%p